name: "Production IAC"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

  push:
    branches: [main]
    paths: [terraform/**]

  pull_request:
    branches: [main]
    paths: [terraform/**]

env:
  AWS_REGION: us-east-2
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  EKS_CLUSTER: eks-cluster

jobs:
# =======================
# APPLY
# =======================
  terraform-apply:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.action == 'apply'

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan -out=planfile
      - run: terraform apply -auto-approve planfile
        if: github.ref == 'refs/heads/main'

# =======================
# DESTROY (MANUAL CLICK)
# =======================
  terraform-destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
      - run: terraform destroy -auto-approve
